language: c
services: docker
install:
    - wget https://raw.githubusercontent.com/xenserver/xenserver-build-env/master/utils/travis-build-repo.sh
script: bash travis-build-repo.sh
sudo: true
env:
    global:
        - REPO_PACKAGE_NAME=xenopsd # TODO: update to xapi-work-queues when the package exists
        - REPO_CONFIGURE_CMD='./configure --enable-tests'
        - REPO_BUILD_CMD=make
        - REPO_TEST_CMD='make test'
